// =====================Login===========================
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

// ====================Forgot password==================
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

// =====================Get Sidebar===========================
export const GET_SIDEBAR = "GET_SIDEBAR";
export const GET_SIDEBAR_SUCCESS = "GET_SIDEBAR_SUCCESS";
export const GET_SIDEBAR_FAILURE = "GET_SIDEBAR_FAILURE";

// ====================ADD_EDIT_USER_SKILL==================
export const ADD_EDIT_USER_SKILL = "ADD_EDIT_USER_SKILL";
export const ADD_EDIT_USER_SKILL_SUCCESS = "ADD_EDIT_USER_SKILL_SUCCESS";
export const ADD_EDIT_USER_SKILL_FAILURE = "ADD_EDIT_USER_SKILL_FAILURE";

// ====================DELETE_USER_SKILL==================
export const DELETE_USER_SKILL = "DELETE_USER_SKILL";
export const DELETE_USER_SKILL_SUCCESS = "DELETE_USER_SKILL_SUCCESS";
export const DELETE_USER_SKILL_FAILURE = "DELETE_USER_SKILL_FAILURE";

// ====================GET_USER_SKILL==================
export const GET_USER_SKILL = "GET_USER_SKILL";
export const GET_USER_SKILL_SUCCESS = "GET_USER_SKILL_SUCCESS";
export const GET_USER_SKILL_FAILURE = "GET_USER_SKILL_FAILURE";

// ====================External Link==================
export const ADD_EDIT_EXTERNAL_LINK_USER = "ADD_EDIT_EXTERNAL_LINK_USER";
export const ADD_EDIT_EXTERNAL_LINK_USER_SUCCESS =
  "ADD_EDIT_EXTERNAL_LINK_USER_SUCCESS";
export const ADD_EDIT_EXTERNAL_LINK_USER_FAILURE =
  "ADD_EDIT_EXTERNAL_LINK_USER_FAILURE";

// ====================Get External Link==================
export const GET_USER_EXTERNAL_LINK = "GET_USER_EXTERNAL_LINK";
export const GET_USER_EXTERNAL_LINK_SUCCESS = "GET_USER_EXTERNAL_LINK_SUCCESS";
export const GET_USER_EXTERNAL_LINK_FAILURE = "GET_USER_EXTERNAL_LINK_FAILURE";

// ====================Reset password==================
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

// ====================Change password==================
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

// ====================Create Family Details==================
export const CREATE_FAMILY_DETAIL = "CREATE_FAMILY_DETAIL";
export const CREATE_FAMILY_DETAIL_SUCCESS = "CREATE_FAMILY_DETAIL_SUCCESS";
export const CREATE_FAMILY_DETAIL_FAILURE = "CREATE_FAMILY_DETAIL_FAILURE";

// ====================Get Family Details==================
export const GET_FAMILY_DETAIL = "GET_FAMILY_DETAIL";
export const GET_FAMILY_DETAIL_SUCCESS = "GET_FAMILY_DETAIL_SUCCESS";
export const GET_FAMILY_DETAIL_FAILURE = "GET_FAMILY_DETAIL_FAILURE";

// ==================== Add Edit Emergency Contact ==================
export const ADD_EDIT_EMERGENCY_CONTACT = "ADD_EDIT_EMERGENCY_CONTACT";
export const ADD_EDIT_EMERGENCY_CONTACT_SUCCESS =
  "ADD_EDIT_EMERGENCY_CONTACT_SUCCESS";
export const ADD_EDIT_EMERGENCY_CONTACT_FAILURE =
  "ADD_EDIT_EMERGENCY_CONTACT_FAILURE";

// ==================== F&F ==================
export const ADD_EDIT_FF = "ADD_EDIT_FF";
export const ADD_EDIT_FF_SUCCESS = "ADD_EDIT_FF_SUCCESS";
export const ADD_EDIT_FF_FAILURE = "ADD_EDIT_FF_FAILURE";

// ==================== F&F ==================
export const GET_FF = "GET_FF";
export const GET_FF_SUCCESS = "GET_FF_SUCCESS";
export const GET_FF_FAILURE = "GET_FF_FAILURE";

// ====================Get Qualification ==================
export const GET_QUALIFICATION = "GET_QUALIFICATION";
export const GET_QUALIFICATION_SUCCESS = "GET_QUALIFICATION_SUCCESS";
export const GET_QUALIFICATION_FAILURE = "GET_QUALIFICATION_FAILURE";

// ==================== Add Edit Qualification ==================
export const ADD_EDIT_QUALIFICATION = "ADD_EDIT_QUALIFICATION";
export const ADD_EDIT_QUALIFICATION_SUCCESS = "ADD_EDIT_QUALIFICATION_SUCCESS";
export const ADD_EDIT_QUALIFICATION_FAILURE = "ADD_EDIT_QUALIFICATION_FAILURE";

// ==================== Delete Qualification ==================
export const DELETE_QUALIFICATION = "DELETE_QUALIFICATION";
export const DELETE_QUALIFICATION_SUCCESS = "DELETE_QUALIFICATION_SUCCESS";
export const DELETE_QUALIFICATION_FAILURE = "DELETE_QUALIFICATION_FAILURE";

// ====================Department Type==================
export const DEPARTMENT_TYPE = "DEPARTMENT_TYPE";
export const DEPARTMENT_TYPE_SUCCESS = "DEPARTMENT_TYPE_SUCCESS";
export const DEPARTMENT_TYPE_FAILURE = "DEPARTMENT_TYPE_FAILURE";

// ====================Designation Type==================
export const DESIGNATION_TYPE = "DESIGNATION_TYPE";
export const DESIGNATION_TYPE_SUCCESS = "DESIGNATION_TYPE_SUCCESS";
export const DESIGNATION_TYPE_FAILURE = "DESIGNATION_TYPE_FAILURE";

// ====================REPORTING TO==================
export const REPORTING_TO_TYPE = "REPORTING_TO_TYPE";
export const REPORTING_TO_TYPE_SUCCESS = "REPORTING_TO_TYPE_SUCCESS";
export const REPORTING_TO_TYPE_FAILURE = "REPORTING_TO_TYPE_FAILURE";

// ==================== Education Type ==================
export const EDUCATION_TYPE = "EDUCATION_TYPE";
export const EDUCATION_TYPE_SUCCESS = "EDUCATION_TYPE_SUCCESS";
export const EDUCATION_TYPE_FAILURE = "EDUCATION_TYPE_FAILURE";

// ====================NEW_EMPLOYEE_CODE==================
export const NEW_EMPLOYEE_CODE = "NEW_EMPLOYEE_CODE";
export const NEW_EMPLOYEE_CODE_SUCCESS = "NEW_EMPLOYEE_CODE_SUCCESS";
export const NEW_EMPLOYEE_CODE_FAILURE = "NEW_EMPLOYEE_CODE_FAILURE";

// ====================CREATE_EMPLOYEE_BASIC_INFO==================
export const CREATE_EMPLOYEE_BASIC_INFO = "CREATE_EMPLOYEE_BASIC_INFO";
export const CREATE_EMPLOYEE_BASIC_INFO_SUCCESS =
  "CREATE_EMPLOYEE_BASIC_INFO_SUCCESS";
export const CREATE_EMPLOYEE_BASIC_INFO_FAILURE =
  "CREATE_EMPLOYEE_BASIC_INFO_FAILURE";

// ====================GET_EMPLOYEE_BASIC_INFO==================
export const GET_EMPLOYEE_BASIC_INFO = "GET_EMPLOYEE_BASIC_INFO";
export const GET_EMPLOYEE_BASIC_INFO_SUCCESS =
  "GET_EMPLOYEE_BASIC_INFO_SUCCESS";
export const GET_EMPLOYEE_BASIC_INFO_FAILURE =
  "GET_EMPLOYEE_BASIC_INFO_FAILURE";
export const RESET_EMPLOYEE_BASIC_INFO = "RESET_EMPLOYEE_BASIC_INFO";

// ====================GET_PLATFORM_TYPES==================
export const GET_PLATFORM_TYPES = "GET_PLATFORM_TYPES";
export const GET_PLATFORM_TYPES_SUCCESS = "GET_PLATFORM_TYPES_SUCCESS";
export const GET_PLATFORM_TYPES_FAILURE = "GET_PLATFORM_TYPES_FAILURE";

// ====================GET EMERGENCY CONTACT==================
export const GET_EMERGENCY_CONTACTS = "GET_EMERGENCY_CONTACTS";
export const GET_EMERGENCY_CONTACTS_SUCCESS = "GET_EMERGENCY_CONTACTS_SUCCESS";
export const GET_EMERGENCY_CONTACTS_FAILURE = "GET_EMERGENCY_CONTACTS_FAILURE";

// ====================DELETE EMERGENCY CONTACT==================
export const DELETE_EMERGENCY_CONTACT = "DELETE_EMERGENCY_CONTACT";
export const DELETE_EMERGENCY_CONTACT_SUCCESS =
  "DELETE_EMERGENCY_CONTACT_SUCCESS";
export const DELETE_EMERGENCY_CONTACT_FAILURE =
  "DELETE_EMERGENCY_CONTACT_FAILURE";

// ====================GET_SKILL_TYPES==================
export const GET_SKILL_TYPES = "GET_SKILL_TYPES";
export const GET_SKILL_TYPES_SUCCESS = "GET_SKILL_TYPES_SUCCESS";
export const GET_SKILL_TYPES_FAILURE = "GET_SKILL_TYPES_FAILURE";

// ====================GET_DOCUMENT_TYPES==================
export const GET_DOCUMENT_TYPES = "GET_DOCUMENT_TYPES";
export const GET_DOCUMENT_TYPES_SUCCESS = "GET_DOCUMENT_TYPES_SUCCESS";
export const GET_DOCUMENT_TYPES_FAILURE = "GET_DOCUMENT_TYPES_FAILURE";

// ====================GET EMPLOYEE DOCUMENTS==================
export const GET_EMPLOYEE_DOCUMENTS = "GET_EMPLOYEE_DOCUMENTS";
export const GET_EMPLOYEE_DOCUMENTS_SUCCESS = "GET_EMPLOYEE_DOCUMENTS_SUCCESS";
export const GET_EMPLOYEE_DOCUMENTS_FAILURE = "GET_EMPLOYEE_DOCUMENTS_FAILURE";

// ====================ADD EDIT EMPLOYEE DOCUMENTS==================
export const ADD_EDIT_EMPLOYEE_DOCUMENTS = "ADD_EDIT_EMPLOYEE_DOCUMENTS";
export const ADD_EDIT_EMPLOYEE_DOCUMENTS_SUCCESS =
  "ADD_EDIT_EMPLOYEE_DOCUMENTS_SUCCESS";
export const ADD_EDIT_EMPLOYEE_DOCUMENTS_FAILURE =
  "ADD_EDIT_EMPLOYEE_DOCUMENTS_FAILURE";

// ====================DELETE EMPLOYEE DOCUMENTS==================
export const DELETE_EMPLOYEE_DOCUMENTS = "DELETE_EMPLOYEE_DOCUMENTS";
export const DELETE_EMPLOYEE_DOCUMENTS_SUCCESS =
  "DELETE_EMPLOYEE_DOCUMENTS_SUCCESS";
export const DELETE_EMPLOYEE_DOCUMENTS_FAILURE =
  "DELETE_EMPLOYEE_DOCUMENTS_FAILURE";

// ====================GET_ADDRESS==================
export const GET_ADDRESS = "GET_ADDRESS";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAILURE = "GET_ADDRESS_FAILURE";

// ====================ADD_EDIT_ADDRESS==================
export const ADD_EDIT_ADDRESS = "ADD_EDIT_ADDRESS";
export const ADD_EDIT_ADDRESS_SUCCESS = "ADD_EDIT_ADDRESS_SUCCESS";
export const ADD_EDIT_ADDRESS_FAILURE = "ADD_EDIT_ADDRESS_FAILURE";

// ====================GET_STATE_TYPES==================
export const GET_STATE_TYPES = "GET_STATE_TYPES";
export const GET_STATE_TYPES_SUCCESS = "GET_STATE_TYPES_SUCCESS";
export const GET_STATE_TYPES_FAILURE = "GET_STATE_TYPES_FAILURE";

// ====================ADD EDIT EMPLOYEE EXPERIENCE==================
export const ADD_EDIT_EMPLOYEE_EXPERIENCE = "ADD_EDIT_EMPLOYEE_EXPERIENCE";
export const ADD_EDIT_EMPLOYEE_EXPERIENCE_SUCCESS =
  "ADD_EDIT_EMPLOYEE_EXPERIENCE_SUCCESS";
export const ADD_EDIT_EMPLOYEE_EXPERIENCE_FAILURE =
  "ADD_EDIT_EMPLOYEE_EXPERIENCE_FAILURE";

// ====================GET EMPLOYEE EXPERIENCE==================
export const GET_EMPLOYEE_EXPERIENCE = "GET_EMPLOYEE_EXPERIENCE";
export const GET_EMPLOYEE_EXPERIENCE_SUCCESS =
  "GET_EMPLOYEE_EXPERIENCE_SUCCESS";
export const GET_EMPLOYEE_EXPERIENCE_FAILURE =
  "GET_EMPLOYEE_EXPERIENCE_FAILURE";

// ====================DELETE EMPLOYEE EXPERIENCE==================
export const DELETE_EMPLOYEE_EXPERIENCE = "DELETE_EMPLOYEE_EXPERIENCE";
export const DELETE_EMPLOYEE_EXPERIENCE_SUCCESS =
  "DELETE_EMPLOYEE_EXPERIENCE_SUCCESS";
export const DELETE_EMPLOYEE_EXPERIENCE_FAILURE =
  "DELETE_EMPLOYEE_EXPERIENCE_FAILURE";

// ====================ADD HOLIDAYS==================
export const ADD_HOLIDAY = "ADD_HOLIDAY";
export const ADD_HOLIDAY_SUCCESS = "ADD_HOLIDAY_SUCCESS";
export const ADD_HOLIDAY_FAILURE = "ADD_HOLIDAY_FAILURE";

// ====================GET HOLIDAYS==================
export const GET_HOLIDAY = "GET_HOLIDAY";
export const GET_HOLIDAY_SUCCESS = "GET_HOLIDAY_SUCCESS";
export const GET_HOLIDAY_FAILURE = "GET_HOLIDAY_FAILURE";

// ====================DELETE HOLIDAYS==================
export const DELETE_HOLIDAY = "DELETE_HOLIDAY";
export const DELETE_HOLIDAY_SUCCESS = "DELETE_HOLIDAY_SUCCESS";
export const DELETE_HOLIDAY_FAILURE = "DELETE_HOLIDAY_FAILURE";

// ====================UPDATE HOLIDAYS==================
export const UPDATE_HOLIDAY = "UPDATE_HOLIDAY";
export const UPDATE_HOLIDAY_SUCCESS = "UPDATE_HOLIDAY_SUCCESS";
export const UPDATE_HOLIDAY_FAILURE = "UPDATE_HOLIDAY_FAILURE";

// ====================PUBLISH HOLIDAYS==================
export const PUBLISH_HOLIDAY = "PUBLISH_HOLIDAY";
export const PUBLISH_HOLIDAY_SUCCESS = "PUBLISH_HOLIDAY_SUCCESS";
export const PUBLISH_HOLIDAY_FAILURE = "PUBLISH_HOLIDAY_FAILURE";

// ====================GET DOCUMENT==================
export const GET_COMPANY_DOCUMENT = "GET_COMPANY_DOCUMENT";
export const GET_COMPANY_DOCUMENT_SUCCESS = "GET_COMPANY_DOCUMENT_SUCCESS";
export const GET_COMPANY_DOCUMENT_FAILURE = "GET_COMPANY_DOCUMENT_FAILURE";

// ====================ADD EDIT COMPANY DOCUMENT==================
export const ADD_EDIT_COMPANY_DOCUMENT = "ADD_EDIT_COMPANY_DOCUMENT";
export const ADD_EDIT_COMPANY_DOCUMENT_SUCCESS =
  "ADD_EDIT_COMPANY_DOCUMENT_SUCCESS";
export const ADD_EDIT_COMPANY_DOCUMENT_FAILURE =
  "ADD_EDIT_COMPANY_DOCUMENT_FAILURE";

// ====================PUBLISH COMPANY DOCUMENT==================
export const PUBLISH_COMPANY_DOCUMENT = "PUBLISH_COMPANY_DOCUMENT";
export const PUBLISH_COMPANY_DOCUMENT_SUCCESS =
  "PUBLISH_COMPANY_DOCUMENT_SUCCESS";
export const PUBLISH_COMPANY_DOCUMENT_FAILURE =
  "PUBLISH_COMPANY_DOCUMENT_FAILURE";

// ====================DELETE COMPANY DOCUMENT==================
export const DELETE_COMPANY_DOCUMENT = "DELETE_COMPANY_DOCUMENT";
export const DELETE_COMPANY_DOCUMENT_SUCCESS =
  "DELETE_COMPANY_DOCUMENT_SUCCESS";
export const DELETE_COMPANY_DOCUMENT_FAILURE =
  "DELETE_COMPANY_DOCUMENT_FAILURE";

// ====================EMAIL COMPANY DOCUMENT==================
export const EMAIL_COMPANY_DOCUMENT = "EMAIL_COMPANY_DOCUMENT";
export const EMAIL_COMPANY_DOCUMENT_SUCCESS = "EMAIL_COMPANY_DOCUMENT_SUCCESS";
export const EMAIL_COMPANY_DOCUMENT_FAILURE = "TOGGLE_COMPANY_DOCUMENT_FAILURE";

// ====================TOGGLE COMPANY DOCUMENT==================
export const TOGGLE_COMPANY_DOCUMENT = "TOGGLE_COMPANY_DOCUMENT";
export const TOGGLE_COMPANY_DOCUMENT_SUCCESS =
  "TOGGLE_COMPANY_DOCUMENT_SUCCESS";
export const TOGGLE_COMPANY_DOCUMENT_FAILURE =
  "TOGGLE_COMPANY_DOCUMENT_FAILURE";

// ====================Get Country==================
export const GET_COUNTRY = "GET_COUNTRY";
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";
export const GET_COUNTRY_FAILURE = "GET_COUNTRY_FAILURE";

// ==================== GET_EMPLOYEE ==================
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_FAILURE = "GET_EMPLOYEE_FAILURE";

// ====================GET_PROJECT_BASIC_DETAIL==================
export const GET_PROJECT_BASIC_DETAIL = "GET_PROJECT_BASIC_DETAIL";
export const GET_PROJECT_BASIC_DETAIL_SUCCESS =
  "GET_PROJECT_BASIC_DETAIL_SUCCESS";
export const GET_PROJECT_BASIC_DETAIL_FAILURE =
  "GET_PROJECT_BASIC_DETAIL_FAILURE";
export const RESET_PROJECT_BASIC_DETAIL = "RESET_PROJECT_BASIC_DETAIL";

// ====================ADD_EDIT_PROJECT_BASIC_DETAIL==================
export const ADD_EDIT_PROJECT_BASIC_DETAIL = "ADD_EDIT_PROJECT_BASIC_DETAIL";
export const ADD_EDIT_PROJECT_BASIC_DETAIL_SUCCESS =
  "ADD_EDIT_PROJECT_BASIC_DETAIL_SUCCESS";
export const ADD_EDIT_PROJECT_BASIC_DETAIL_FAILURE =
  "ADD_EDIT_PROJECT_BASIC_DETAIL_FAILURE";

// ====================SEND_PROJECT_FOR_REVIEW==================
export const SEND_PROJECT_FOR_REVIEW = "SEND_PROJECT_FOR_REVIEW";
export const SEND_PROJECT_FOR_REVIEW_SUCCESS =
  "SEND_PROJECT_FOR_REVIEW_SUCCESS";
export const SEND_PROJECT_FOR_REVIEW_FAILURE =
  "SEND_PROJECT_FOR_REVIEW_FAILURE";

// ====================UPDATE_PROJECT_REVIEW==================
export const UPDATE_PROJECT_REVIEW = "UPDATE_PROJECT_REVIEW";
export const UPDATE_PROJECT_REVIEW_SUCCESS = "UPDATE_PROJECT_REVIEW_SUCCESS";
export const UPDATE_PROJECT_REVIEW_FAILURE = "SEND_PROJECT_FOR_REVIEW_FAILURE";

// ====================GET_PROJECT_MILESTONE==================
export const GET_PROJECT_MILESTONE = "GET_PROJECT_MILESTONE";
export const GET_PROJECT_MILESTONE_SUCCESS = "GET_PROJECT_MILESTONE_SUCCESS";
export const GET_PROJECT_MILESTONE_FAILURE = "GET_PROJECT_MILESTONE_FAILURE";

// ====================ADD_EDIT_PROJECT_MILESTONE==================
export const ADD_EDIT_PROJECT_MILESTONE = "ADD_EDIT_PROJECT_MILESTONE";
export const ADD_EDIT_PROJECT_MILESTONE_SUCCESS =
  "ADD_EDIT_PROJECT_MILESTONE_SUCCESS";
export const ADD_EDIT_PROJECT_MILESTONE_FAILURE =
  "ADD_EDIT_PROJECT_MILESTONE_FAILURE";

// ====================DELETE_PROJECT_MILESTONE==================
export const DELETE_PROJECT_MILESTONE = "DELETE_PROJECT_MILESTONE";
export const DELETE_PROJECT_MILESTONE_SUCCESS =
  "DELETE_PROJECT_MILESTONE_SUCCESS";
export const DELETE_PROJECT_MILESTONE_FAILURE =
  "DELETE_PROJECT_MILESTONE_FAILURE";

// ====================GET_CLIENT_DETAIL==================
export const GET_CLIENT_DETAIL = "GET_CLIENT_DETAIL";
export const GET_CLIENT_DETAIL_SUCCESS = "GET_CLIENT_DETAIL_SUCCESS";
export const GET_CLIENT_DETAIL_FAILURE = "GET_CLIENT_DETAIL_FAILURE";

// ====================ADD_EDIT_CLIENT_DETAIL==================
export const ADD_EDIT_CLIENT_DETAIL = "ADD_EDIT_CLIENT_DETAIL";
export const ADD_EDIT_CLIENT_DETAIL_SUCCESS = "ADD_EDIT_CLIENT_DETAIL_SUCCESS";
export const ADD_EDIT_CLIENT_DETAIL_FAILURE = "ADD_EDIT_CLIENT_DETAIL_FAILURE";

// ====================GET_PROJECT_RESOURCE==================
export const GET_PROJECT_RESOURCE = "GET_PROJECT_RESOURCE";
export const GET_PROJECT_RESOURCE_SUCCESS = "GET_PROJECT_RESOURCE_SUCCESS";
export const GET_PROJECT_RESOURCE_FAILURE = "GET_PROJECT_RESOURCE_FAILURE";

// ====================ADD_EDIT_PROJECT_RESOURCE==================
export const ADD_EDIT_PROJECT_RESOURCE = "ADD_EDIT_PROJECT_RESOURCE";
export const ADD_EDIT_PROJECT_RESOURCE_SUCCESS =
  "ADD_EDIT_PROJECT_RESOURCE_SUCCESS";
export const ADD_EDIT_PROJECT_RESOURCE_FAILURE =
  "ADD_EDIT_PROJECT_RESOURCE_FAILURE";

// ====================DELETE_PROJECT_RESOURCE==================
export const DELETE_PROJECT_RESOURCE = "DELETE_PROJECT_RESOURCE";
export const DELETE_PROJECT_RESOURCE_SUCCESS =
  "DELETE_PROJECT_RESOURCE_SUCCESS";
export const DELETE_PROJECT_RESOURCE_FAILURE =
  "DELETE_PROJECT_RESOURCE_FAILURE";

// ====================GET_ESCALATION==================
export const GET_ESCALATION = "GET_ESCALATION";
export const GET_ESCALATION_SUCCESS = "GET_ESCALATION_SUCCESS";
export const GET_ESCALATION_FAILURE = "GET_ESCALATION_FAILURE";

// ====================DELETE_ESCALATION==================
export const DELETE_ESCALATION = "DELETE_ESCALATION";
export const DELETE_ESCALATION_SUCCESS = "DELETE_ESCALATION_SUCCESS";
export const DELETE_ESCALATION_FAILURE = "DELETE_ESCALATION_FAILURE";

// ====================ADD_EDIT_ESCALATION==================
export const ADD_EDIT_ESCALATION = "ADD_EDIT_ESCALATION";
export const ADD_EDIT_ESCALATION_SUCCESS = "ADD_EDIT_ESCALATION_SUCCESS";
export const ADD_EDIT_ESCALATION_FAILURE = "ADD_EDIT_ESCALATION_FAILURE";

// ====================GET_PROJECT_CHANGE_REQUEST==================
export const GET_PROJECT_CHANGE_REQUEST = "GET_PROJECT_CHANGE_REQUEST";
export const GET_PROJECT_CHANGE_REQUEST_SUCCESS =
  "GET_PROJECT_CHANGE_REQUEST_SUCCESS";
export const GET_PROJECT_CHANGE_REQUEST_FAILURE =
  "GET_PROJECT_CHANGE_REQUEST_FAILURE";

// ====================ADD_EDIT_PROJECT_DOCUMENT==================
export const ADD_EDIT_PROJECT_CHANGE_REQUEST =
  "ADD_EDIT_PROJECT_CHANGE_REQUEST";
export const ADD_EDIT_PROJECT_CHANGE_REQUEST_SUCCESS =
  "ADD_EDIT_PROJECT_CHANGE_REQUEST_SUCCESS";
export const ADD_EDIT_PROJECT_CHANGE_REQUEST_FAILURE =
  "ADD_EDIT_PROJECT_CHANGE_REQUEST_FAILURE";

// ====================DELETE_PROJECT_CHANGE_REQUEST==================
export const DELETE_PROJECT_CHANGE_REQUEST = "DELETE_PROJECT_CHANGE_REQUEST";
export const DELETE_PROJECT_CHANGE_REQUEST_SUCCESS =
  "DELETE_PROJECT_CHANGE_REQUEST_SUCCESS";
export const DELETE_PROJECT_CHANGE_REQUEST_FAILURE =
  "DELETE_PROJECT_CHANGE_REQUEST_FAILURE";

// ====================GET_PROJECT_DOCUMENT==================
export const GET_PROJECT_DOCUMENT = "GET_PROJECT_DOCUMENT";
export const GET_PROJECT_DOCUMENT_SUCCESS = "GET_PROJECT_DOCUMENT_SUCCESS";
export const GET_PROJECT_DOCUMENT_FAILURE = "GET_PROJECT_DOCUMENT_FAILURE";

// ====================ADD_EDIT_PROJECT_DOCUMENT==================
export const ADD_EDIT_PROJECT_DOCUMENT = "ADD_EDIT_PROJECT_DOCUMENT";
export const ADD_EDIT_PROJECT_DOCUMENT_SUCCESS =
  "ADD_EDIT_PROJECT_DOCUMENT_SUCCESS";
export const ADD_EDIT_PROJECT_DOCUMENT_FAILURE =
  "ADD_EDIT_PROJECT_DOCUMENT_FAILURE";

// ====================GET_PROJECT_DOCUMENT==================
export const DELETE_PROJECT_DOCUMENT = "DELETE_PROJECT_DOCUMENT";
export const DELETE_PROJECT_DOCUMENT_SUCCESS =
  "DELETE_PROJECT_DOCUMENT_SUCCESS";
export const DELETE_PROJECT_DOCUMENT_FAILURE =
  "DELETE_PROJECT_DOCUMENT_FAILURE";

// ====================GET_PROJECT_LIST==================
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";
export const GET_PROJECT_LIST_SUCCESS = "GET_PROJECT_LIST_SUCCESS";
export const GET_PROJECT_LIST_FAILURE = "GET_PROJECT_LIST_FAILURE";

// ====================GET_CLIENT_COMPANY_LIST============
export const GET_CLIENT_COMPANY_LIST = "GET_CLIENT_COMPANY_LIST";
export const GET_CLIENT_COMPANY_LIST_SUCCESS =
  "GET_CLIENT_COMPANY_LIST_SUCCESS";
export const GET_CLIENT_COMPANY_LIST_FAILURE =
  "GET_CLIENT_COMPANY_LIST_FAILURE";

// ================GET_ESCALATION_TYPE====================
export const GET_ESCALATION_TYPE = "GET_ESCALATION_TYPE";
export const GET_ESCALATION_TYPE_SUCCESS = "GET_ESCALATION_TYPE_SUCCESS";
export const GET_ESCALATION_TYPE_FAILURE = "GET_ESCALATION_TYPE_FAILURE";

// ================GET_PROJECT============================
export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";

// ================GET_PROJECT============================
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

// ===================== Add Company ======================
export const ADD_COMPANY = "ADD_COMPANY";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAILURE = "ADD_COMPANY_FAILURE";

// ====================ADD_INTERVIEW==================
export const ADD_INTERVIEW = "ADD_INTERVIEW";
export const ADD_INTERVIEW_SUCCESS = "ADD_INTERVIEW_SUCCESS";
export const ADD_INTERVIEW_FAILURE = "ADD_INTERVIEW_FAILURE";

// ====================GET_INTERVIEW_DATA==================
export const GET_INTERVIEW_DATA = "GET_INTERVIEW_DATA";
export const GET_INTERVIEW_DATA_SUCCESS = "GET_INTERVIEW_DATA_SUCCESS";
export const GET_INTERVIEW_DATA_FAILURE = "GET_INTERVIEW_DATA_FAILURE";

// ====================ADD_EDIT_DEPARTMENT==================
export const ADD_EDIT_DEPARTMENT = "ADD_EDIT_DEPARTMENT";
export const ADD_EDIT_DEPARTMENT_SUCCESS = "ADD_EDIT_DEPARTMENT_SUCCESS";
export const ADD_EDIT_DEPARTMENT_FAILURE = "ADD_EDIT_DEPARTMENT_FAILURE";

// ====================ADD_EDIT_DESIGNATION==================
export const ADD_EDIT_DESIGNATION = "ADD_EDIT_DESIGNATION";
export const ADD_EDIT_DESIGNATION_SUCCESS = "ADD_EDIT_DESIGNATION_SUCCESS";
export const ADD_EDIT_DESIGNATION_FAILURE = "ADD_EDIT_DESIGNATION_FAILURE";

// ====================GET_DESIGNATION==================
export const GET_DESIGNATION_FILTER = "GET_DESIGNATION_FILTER";
export const GET_DESIGNATION_FILTER_SUCCESS = "GET_DESIGNATION_FILTER_SUCCESS";
export const GET_DESIGNATION_FILTER_FAILURE = "GET_DESIGNATION_FILTER_FAILURE";

// ====================ADD_EDIT_RESOURCE==================
export const ADD_EDIT_RESOURCE = "ADD_EDIT_RESOURCE";
export const ADD_EDIT_RESOURCE_SUCCESS = "ADD_EDIT_RESOURCE_SUCCESS";
export const ADD_EDIT_RESOURCE_FAILURE = "ADD_EDIT_RESOURCE_FAILURE";

// ====================GET_RESOURCE==================
export const GET_RESOURCE = "GET_RESOURCE";
export const GET_RESOURCE_SUCCESS = "GET_RESOURCE_SUCCESS";
export const GET_RESOURCE_FAILURE = "GET_RESOURCE_FAILURE";

// ====================DELETE_RESOURCE==================
export const DELETE_RESOURCE = "DELETE_RESOURCE";
export const DELETE_RESOURCE_SUCCESS = "DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_FAILURE = "DELETE_RESOURCE_FAILURE";

// ====================SEND_INTIMATION-EMAIL==================
export const POST_SEND_INTIMATION = "POST_SEND_INTIMATION";
export const POST_SEND_INTIMATION_SUCCESS = "POST_SEND_INTIMATION_SUCCESS";
export const POST_SEND_INTIMATION_FAILURE = "POST_SEND_INTIMATION_FAILURE";

// ====================SEND_INTIMATION-EMAIL==================
export const POST_SEND_INTIMATION_TO_TEAM = "POST_SEND_INTIMATION_TO_TEAM";
export const POST_SEND_INTIMATION_TO_TEAM_SUCCESS =
  "POST_SEND_INTIMATION_TO_TEAM_SUCCESS";
export const POST_SEND_INTIMATION_TO_TEAM_FAILURE =
  "POST_SEND_INTIMATION_TO_TEAM_FAILURE";

// ====================PROJECT COUNT==================
export const GET_PROJECT_COUNT = "GET_PROJECT_COUNT";
export const GET_PROJECT_COUNT_SUCCESS = "GET_PROJECT_COUNT_SUCCESS";
export const GET_PROJECT_COUNT_FAILURE = "GET_PROJECT_COUNT_FAILURE";

//====================GET SKILL MATRIX================
export const GET_SKILL_MATRIX = "GET_SKILL_MATRIX";
export const GET_SKILL_MATRIX_SUCCESS = "GET_SKILL_MATRIX_SUCCESS";
export const GET_SKILL_MATRIX_FAILURE = "GET_SKILL_MATRIX_FAILURE";

// ====================GET_CONFIG_DATA==================
export const GET_CONFIG_DATA = "GET_CONFIG_DATA";
export const GET_CONFIG_DATA_SUCCESS = "GET_CONFIG_DATA_SUCCESS";
export const GET_CONFIG_DATA_FAILURE = "GET_CONFIG_DATA_FAILURE";

// ====================GET_CONFIG_EMPLOYEE_DATA==================
export const GET_CONFIG_EMPLOYEE_DATA = "GET_CONFIG_EMPLOYEE_DATA";
export const GET_CONFIG_EMPLOYEE_DATA_SUCCESS =
  "GET_CONFIG_EMPLOYEE_DATA_SUCCESS";
export const GET_CONFIG_EMPLOYEE_DATA_FAILURE =
  "GET_CONFIG_EMPLOYEE_DATA_FAILURE";

// ====================UPDATE_CONFIG_EMPLOYEE_DATA==================
export const UPDATE_CONFIG_EMPLOYEE_DATA = "UPDATE_CONFIG_EMPLOYEE_DATA";
export const UPDATE_CONFIG_EMPLOYEE_DATA_SUCCESS =
  "UPDATE_CONFIG_EMPLOYEE_DATA_SUCCESS";
export const UPDATE_CONFIG_EMPLOYEE_DATA_FAILURE =
  "UPDATE_CONFIG_EMPLOYEE_DATA_FAILURE";

// ====================GET_PROJECT_REPORT==================
export const GET_PROJECT_REPORT = "GET_PROJECT_REPORT";
export const GET_PROJECT_REPORT_SUCCESS = "GET_PROJECT_REPORT_SUCCESS";
export const GET_PROJECT_REPORT_FAILURE = "GET_PROJECT_REPORT_FAILURE";

// ====================GET_CONFIG_DESIGNATION_DATA==================
export const GET_CONFIG_DESIGNATION_DATA = "GET_CONFIG_DESIGNATION_DATA";
export const GET_CONFIG_DESIGNATION_DATA_SUCCESS =
  "GET_CONFIG_DESIGNATION_DATA_SUCCESS";
export const GET_CONFIG_DESIGNATION_DATA_FAILURE =
  "GET_CONFIG_DESIGNATION_DATA_FAILURE";

// ====================UPDATE_CONFIG_DESIGNATION_DATA==================
export const UPDATE_CONFIG_DESIGNATION_DATA = "UPDATE_CONFIG_DESIGNATION_DATA";
export const UPDATE_CONFIG_DESIGNATION_DATA_SUCCESS =
  "UPDATE_CONFIG_DESIGNATION_DATA_SUCCESS";
export const UPDATE_CONFIG_DESIGNATION_DATA_FAILURE =
  "UPDATE_CONFIG_DESIGNATION_DATA_FAILURE";
